CREATE TABLE product_details (
  lid int(11) NOT NULL,
  title varchar(128) DEFAULT NULL,
  subtitle varchar(128) DEFAULT NULL,
  price decimal(10,2) DEFAULT NULL
);
INSERT INTO product_details (lid,title,subtitle,price) VALUES
(1,'吉祥手办','回味最初的游戏时光',138),
(2,'“昕”动神武 小昕手办','小昕陪你玩神武',98),
(3,'《神武3》丝巾礼盒','限量神武3主题丝巾，礼赞爱情',188),
(4,'吉祥小跨包','《神武3》周边挎包，吉祥时刻伴你左右',49),
(5,'神武3唯美纸雕灯','于黑暗中发出光芒，指引你找寻我的方向',131),
(6,'嵩鼠礼包(嵩鼠公仔+嵩鼠T恤)','呆萌可爱的超人气小嵩鼠，陪你度过青嵩岁月',168),
(7,'嵩鼠公仔','呆萌可爱的超人气小嵩鼠，陪你度过青嵩岁月',118),
(8,'神牛公仔','一只爱好旅游的神奇奶牛，从神武穿越而来陪伴你',98),
(9,'神武3桃子公仔','神武3全新萌物桃子精灵“桃”气登场',118),
(10,'灵犀公仔','柔软舒适的毛绒面料，精选电绣工艺，采用优质PP棉填充',98),
(11,'吉祥公仔','可爱又呆萌的小吉祥，手感舒适',48),
(12,'小飞猪公仔','柔软舒适的毛绒面料，精选电绣工艺，采用优质PP棉填充',39);

CREATE TABLE product_detail_pic(
  pid int(11) NOT NULL,
  product_detail_id int(11) DEFAULT NULL,
  sm varchar(128) DEFAULT NULL
); 
 
 INSERT INTO product_detail_pic (pid,product_detail_id,sm) VALUES
 (1,1,'require("../assets/xiaoji1.jpg")'),
 (2,1,'require("../assets/xiaoji2.jpg")'),
 (3,1,'require("../assets/xiaoji3.jpg")'),
 (4,2,'require("../assets/xiaohong1.jpg")'),
 (5,2,'require("../assets/xiaohong2.jpg")'),
 (6,3,'require("../assets/lihe1.jpg")'),
 (7,3,'require("../assets/lihe2.jpg")'),
 (8,3,'require("../assets/lihe3.jpg")'),
 (9,3,'require("../assets/lihe4.jpg")'),
 (10,4,'require("../assets/xiaobao1.jpg")'),
 (11,4,'require("../assets/xiaobao2.jpg")'),
 (12,4,'require("../assets/xiaobao3.jpg")'),
 (13,5,'require("../assets/deng1.jpg")'),
 (14,5,'require("../assets/deng2.jpg")'),
 (15,5,'require("../assets/deng3.jpg")'),
 (16,5,'require("../assets/deng4.jpg")'),
 (17,6,'require("../assets/libao1.jpg")'),
 (18,6,'require("../assets/libao2.jpg")'),
 (19,6,'require("../assets/libao3.jpg")'),
 (20,6,'require("../assets/libao4.jpg")'),
 (21,7,'require("../assets/shu1.jpg")'),
 (22,7,'require("../assets/shu2.jpg")'),
 (23,7,'require("../assets/shu3.jpg")'),
 (24,7,'require("../assets/shu4.jpg")'),
 (25,8,'require("../assets/niu1.jpg")'),
 (26,8,'require("../assets/niu2.jpg")'),
 (27,8,'require("../assets/niu3.jpg")'),
 (28,8,'require("../assets/niu4.jpg")'),
 (29,9,'require("../assets/tao1.jpg")'),
 (30,9,'require("../assets/tao2.png")'),
 (31,9,'require("../assets/tao3.png")'),
 (32,9,'require("../assets/tao4.png")'),
 (33,10,'require("../assets/xiniu1.jpg")'),
 (34,10,'require("../assets/xiniu2.jpg")'),
 (35,10,'require("../assets/xiniu3.jpg")'),
 (36,10,'require("../assets/xiniu4.jpg")'),
 (37,11,'require("../assets/xiaohuang.jpg")'),
 (38,11,'require("../assets/xiaohuang2.jpg")'),
 (39,11,'require("../assets/xiaohuang3.jpg")'),
 (40,12,'require("../assets/zhu1.jpg")'),
 (41,12,'require("../assets/zhu2.jpg")'),
 (42,12,'require("../assets/zhu3.jpg")'),
 (43,12,'require("../assets/zhu4.jpg")');